
library(seqinr)
library(dplyr)

proteasome = read.fasta("data/structure/Swissprot_20S_standard_Proteasome.fasta",
                        seqtype = "AA")

names(proteasome)
activeSites = c(b1 = "P28072", b2 = "Q99436", b5 = "P28074")

b1 = proteasome[grep(activeSites["b1"], names(proteasome))] %>% unlist() %>% as.character()
b2 = proteasome[grep(activeSites["b2"], names(proteasome))] %>% unlist() %>% as.character()
b5 = proteasome[grep(activeSites["b5"], names(proteasome))] %>% unlist() %>% as.character()


# remove propeptides
b1m = b1[35:length(b1)]
b2m = b2[44:length(b2)]
b5m = b5[60:length(b5)]


b1m[c(17,19,33,47,130,167,170)]
b2m[c(17,19,33,47,129,166,169)]
b5m[c(17,19,33,47,130,167,170)]

yeastb5 = "TTTLAFRFQGGIIVAVDSRATAGNWVASQTVKKVIEINPFLLGTMAGGAADCQFWETWLGSQCRLHELREKERISVAAASKILSNLVYQYKGAGLSMGTMICGYTRKEGPTIYYVDSDGTRLKGDIFCVGSGQTFAYGVLDSNYKWDLSVEDALYLGKRSILAAAHRDAYSGGSVNLYHVTEDGWIYHGNHDVGELFWKVKEEEGSFNNVIG"
yeastb5 = strsplit(yeastb5, "") %>% unlist()
yeastb5[c(17,19,33,131,168,171)]
yeastb5[c(17,19,33,129,166,169)]


arabidopisb5 = "TTTLAFIFKEGVMVAADSRASMGGYISSQSVKKIIEINPYMLGTMAGGAADCQFWHRNLGIKCRLHELANKRRISVSGASKLLANMLYSYRGMGLSVGTMIAGWDETGPGLYYVDNEGGRLKGDRFSVGSGSPYAYGVLDSGYKFDMSVEEASELARRSIYHATFRDGASGGVASVYHVGPQGWTKLSGDDVGELHYHYYPVAPITAEHVMEEAAE"
arabidopisb5 = strsplit(arabidopisb5, "") %>% unlist()
arabidopisb5[c(17,19,33,47,130,167,170)]


dictosteliumb5 = "TTTLAFVYGGGIIVSVDSKSTQGPYVASRSVKKVIEITPTLLGTMAGGAADCSFWERELGRRCRLYELRNKELISVAAASKILANIVYSYKGYGLSMGTMITGWDKTGPQLYYVDNDGTRLHGQRFSCGSGSTYAYGVLDTGFKWDMNDEEAYELGRRAVYHATHRDAYSGGAINVYHVQKDGWKKISSDDCFKLYQKYYNIVPINKPAN"
dictosteliumb5 = strsplit(dictosteliumb5, "") %>% unlist()
dictosteliumb5[c(17,19,33,47,130,167,170)]

archaeb5 = "TTTVGITLKDAVIMATERRVTMENFIMHKNGKKLFQIDTYTGMTIAGLVGDAQVLVRYMKAELELYRLQRRVNMPIEAVATLLSNMLNQVKYMPYMVQLLVGGIDTAPHVFSIDAAGGSVEDIYASTGSGSPFVYGVLESQYSEKMTVDEGVDLVIRAISAAKQRDSASGGMIDVAVITRKDGYVQLPTDQIESRIRKLGLIL"
archaeb5 = strsplit(archaeb5, "") %>% unlist()
archaeb5[c(17,19,33,47,129,166,169)]



humanimmunob5 = "TTTLAFKFQHGVIAAVDSRASAGSYISALRVNKVIEINPYLLGTMSGCAADCQYWERLLAKECRLYYLRNGERISVSAASKLLSNMMCQYRGMGLSMGSMICGWDKKGPGLYYVDEHGTRLSGNMFSTGSGNTYAYGVMDSGYRPNLSPEEAYDLGRRAIAYATHRDSYSGGVVNMYHMKEDGWVKVESTDVSDLLHQYREANQ"
humanimmunob5 = strsplit(humanimmunob5, "") %>% unlist()
humanimmunob5[c(17,19,33,47,130,167,170)]

humanthymob5 = "TTTLAFRFRHGVIAAADTRSSCGSYVACPASCKVIPVHQHLLGTTSGTSADCATWYRVLQRELRLRELREGQLPSVASAAKLLSAMMSQYRGLDLCVATALCGWDRSGPELFYVYSDGTRLQGDIFSVGSGSPYAYGVLDRGYRYDMSTQEAYALARCAVAHATHRDAYSGGSVDLFHVRESGWEHVSRSDACVLYVELQKLLEPEPEEDASHAHPEPATAHRAAEDRELSVGPGEVTPGDSRMPAGTETV"
humanthymob5 = strsplit(humanthymob5, "") %>% unlist()
humanthymob5[c(17,19,33,47,130,167,170)]



